### ISSUE TITLE
Basic work of the blog

### ISSUE THREAD

**Issue by yuyang-yy** [yuyang-yy/yuyang-yy.github.io#1]
# Tasks to set up a basic blog
- [x] configure the basic settings of the blog
- [x] remove the Disqus feature in the blog template
- [x] add Analytics feature to the blog
- [x] write my first blog
